# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.utils import Buffer

class Ed25519PrivateKey:
    def sign(self, data: Buffer) -> bytes: ...
    def sign_prehashed(
        self, data: Buffer, context: Buffer | None = None
    ) -> bytes: ...
    def public_key(self) -> ed25519.Ed25519PublicKey: ...
    def private_bytes_raw(self) -> bytes: ...
    def private_bytes(
        self,
        encoding: object,
        format: object,
        encryption_algorithm: object,
    ) -> bytes: ...

class Ed25519PublicKey:
    def verify(self, signature: Buffer, data: Buffer) -> None: ...
    def verify_prehashed(
        self,
        signature: Buffer,
        data: Buffer,
        context: Buffer | None = None,
    ) -> None: ...
    def public_bytes_raw(self) -> bytes: ...
    def public_bytes(
        self,
        encoding: object,
        format: object,
    ) -> bytes: ...

def generate_key() -> ed25519.Ed25519PrivateKey: ...
def from_private_bytes(data: Buffer) -> ed25519.Ed25519PrivateKey: ...
def from_public_bytes(data: bytes) -> ed25519.Ed25519PublicKey: ...
